added imlib checks
Tomas-M/xlunch pull request #27
Opened 2017-07-15 00:44 UTC by dagelf

Prevent imlib logging a lot of errors to the console for icons that don't work...

2017-07-15 06:40 UTC, Tomas-M commented on xlunch.c
> +                      if (image) { imlib_blend_image_onto_image(image, 0, 0, 0, w, h,
Hm, this is already in if (image) block, why would this help?

2017-07-15 20:11 UTC, Tomas-M requested changes
I am not sure if all the modifications are really necessary.

2017-07-16 13:51 UTC, dagelf commented
That one's unnecessary, the others not as they prevent asking imlib to free
nulls, littering the error log with hundreds of messages. A better fix
would be to break earlier if null images are returned.

Op 15 Jul 2017 22:11, het "Tomas-M" <notifications@github.com> geskryf:

*@Tomas-M* requested changes on this pull request.

I am not sure if all the modifications are really necessary.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Tomas-M/xlunch/pull/27#pullrequestreview-50196754>, or mute
the thread
<https://github.com/notifications/unsubscribe-auth/AAw_RDfaj3lSuxIB6Zogcqaq0-g2t0epks5sORzygaJpZM4OY3e8>
.

2017-08-07 17:37 UTC, merged

2017-08-07 17:38 UTC, Tomas-M commented
I'm lazy to write it better so I just merged your patch. Thank you;